name: Update Kanban Table in README

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  update-kanban:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Generate kanban markdown
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python .github/scripts/kanban_to_readme.py

      - name: Commit changes
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git add README.md
          git commit -m "Update Kanban table in README [auto]" || echo "No changes to commit"
          git push
